// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// H H is a shortcut for map[string]interface{}
//
// swagger:model H
type H map[string]interface{}

// Validate validates this h
func (m H) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this h based on context it is used
func (m H) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
